src/objects/CB_Block__c.object
<CustomObject>
    <description>This object stores the blocks associated to quadrant. We can have 4 blocks per quadrants.</description>
    <fields>
        <fullName>CB_Block_Name__c</fullName>
        <description>This field represents the Name of the Block(belongs to Quadrant), which would be displayed along with the image on the Quadrant block.</description>
        <inlineHelpText>This field represents the Name of the Quadrant, which would be displayed along with the image on the Quadrant block.</inlineHelpText>
        <label>Block Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Cost__c</fullName>
        <description>Cost of Opening the block</description>
        <inlineHelpText>Cost of Opening the block</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Quadrant__c</fullName>
        <description>Quadrant to which this block belongs.</description>
        <inlineHelpText>Quadrant to which this block belongs.</inlineHelpText>
        <label>Quadrant</label>
        <referenceTo>CB_Quadrant__c</referenceTo>
        <relationshipLabel>Block</relationshipLabel>
        <relationshipName>Block</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>Sequence of the Block to be shown on the UI, It will also maintain the levels.</description>
        <inlineHelpText>Sequence of the Block to be shown on the UI, It will also maintain the levels.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Block</label>
    <nameField>
        <displayFormat>Block - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_City__c.object
<CustomObject>
    <description>The Master City records</description>
    <fields>
        <fullName>CB_City_Name__c</fullName>
        <description>Name of the city.</description>
        <inlineHelpText>Name of the city.</inlineHelpText>
        <label>City Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Image_URL__c</fullName>
        <description>Image URL of City. We have taken it as a text, because we may save images in static resource and can give only path.</description>
        <inlineHelpText>Image URL of City.</inlineHelpText>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>City</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Game_User__c.object
<CustomObject>
    <description>A user of City Builder Game</description>
    <fields>
        <fullName>CB_Title__c</fullName>
        <defaultValue>&quot;City Janitor&quot;</defaultValue>
        <description>Title of the User in the Game</description>
        <inlineHelpText>Title of the User in the Game</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce User associated with the Game User</description>
        <inlineHelpText>Salesforce User associated with the Game User</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Game_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Quadrant__c.object
<CustomObject>
    <description>One city may contain multiple Quadrant. One quadrant is made up of 4 blocks.</description>
    <fields>
        <fullName>CB_City__c</fullName>
        <description>This field represents the Master detail relationship with the city object.</description>
        <inlineHelpText>City to which quadrant belongs</inlineHelpText>
        <label>City</label>
        <referenceTo>CB_City__c</referenceTo>
        <relationshipLabel>Quadrants</relationshipLabel>
        <relationshipName>Quadrants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Quadrant_Name__c</fullName>
        <description>This field represents the Name of the Quadrant, which would be displayed along with the image on the Quadrant block.</description>
        <inlineHelpText>This field represents the Name of the Quadrant.</inlineHelpText>
        <label>Quadrant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>Sequence of the Quadrant to be shown on the UI, It will also maintain the levels.</description>
        <inlineHelpText>Sequence of the Quadrant to be shown on the UI, It will also maintain the levels.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quadrant</label>
    <nameField>
        <displayFormat>Quadrant - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quadrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_Solution_Option__c.object
<CustomObject>
    <description>Each story has a set of solutions. These are configurable, means we can configure the datatype of the solution options.</description>
    <fields>
        <fullName>CB_Reward__c</fullName>
        <description>Reward amount received by the user, by selecting the option. It&apos;s negative  for Bad Answers</description>
        <inlineHelpText>Reward amount received by the user, by selecting the option. It&apos;s negative  for Bad Answers</inlineHelpText>
        <label>Reward</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Score__c</fullName>
        <description>Score would assigned to each Solution option. Based on the solution option selection and score further actions would be taken.</description>
        <inlineHelpText>Score would assigned to each Solution option. Based on the solution option selection and score further actions would be taken.</inlineHelpText>
        <label>Score</label>
        <picklist>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>This field maintains the Sequence in which solution options to be displayed.</description>
        <inlineHelpText>This field maintains the Sequence in which solution options to be displayed.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CB_Solution_Selection_Description__c</fullName>
        <description>This field contains the description, which would be seen after user selects the option. It will give detailed description of the option, chosen.</description>
        <inlineHelpText>This field contains the description, which would be seen after user selects the option. It will give detailed description of the option, chosen(With reasoning).</inlineHelpText>
        <label>Solution Selection Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CB_Solution_Text__c</fullName>
        <description>This field contains the solution option text, which user is going to select from UI.</description>
        <inlineHelpText>This field contains the solution option text, which user is going to select from UI.</inlineHelpText>
        <label>Solution Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CB_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Story to which solution belongs.</description>
        <inlineHelpText>Story to which solution belongs.</inlineHelpText>
        <label>Story</label>
        <referenceTo>CB_Story__c</referenceTo>
        <relationshipLabel>Solutions Options</relationshipLabel>
        <relationshipName>Solutions_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution Option</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Solution Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Story__c.object
<CustomObject>
    <description>Each block has one scenario (story) that the player reads. This object stores the stories associated with blocks.</description>
    <fields>
        <fullName>CB_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the relation to Block object.</description>
        <inlineHelpText>Block to which Story belongs</inlineHelpText>
        <label>Block</label>
        <referenceTo>CB_Block__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Solution_Data_Type__c</fullName>
        <description>This field represents the configuratble data type. You can configure the solution option type to be shown on UI. We can add more values/configure according to business need.</description>
        <inlineHelpText>This field represents the configuratble data type.</inlineHelpText>
        <label>Solution Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CB_Story_Text__c</fullName>
        <description>Story text for which user has to select solution option.</description>
        <inlineHelpText>Story text for which user has to select solution option.</inlineHelpText>
        <label>Story Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>Story - {0000}</displayFormat>
        <label>Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Story_Answer__c.object
<CustomObject>
    <description>User Selected Answer for the Story</description>
    <fields>
        <fullName>CB_Block_Cost__c</fullName>
        <description>Cost of the Block for this Story</description>
        <inlineHelpText>Cost of the Block for this Story</inlineHelpText>
        <label>Block Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Game_User__c</fullName>
        <label>Game User</label>
        <referenceTo>CB_Game_User__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>CB_Game_User</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Solution_Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The solution, user has selected for their story.</description>
        <inlineHelpText>The solution, user has selected for their story.</inlineHelpText>
        <label>Solution Option</label>
        <referenceTo>CB_Solution_Option__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>Solution_Option</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>CB_Story__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>Story_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Won__c</fullName>
        <description>Amount won by the user, on selecting the option</description>
        <inlineHelpText>Amount won by the user, on selecting the option.</inlineHelpText>
        <label>Won</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Story Answer</label>
    <nameField>
        <displayFormat>Story Answer - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Story Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_User_Block__c.object
<CustomObject>
    <fields>
        <fullName>CB_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the block user has completed.</description>
        <inlineHelpText>This field represents the block user has completed.</inlineHelpText>
        <label>Block</label>
        <referenceTo>CB_Block__c</referenceTo>
        <relationshipName>User_Block_Completions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the user completed this block</description>
        <inlineHelpText>Has the user completed this block</inlineHelpText>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CB_Game_User__c</fullName>
        <label>Game User</label>
        <referenceTo>CB_Game_User__c</referenceTo>
        <relationshipLabel>User Block</relationshipLabel>
        <relationshipName>User_Block_Completions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Block</label>
    <nameField>
        <displayFormat>User Block -{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CB_TestData.cls
/**
 * Class holding static method to create test data used by test classes
 */
public with sharing class CB_TestData {

	public static final String CITY_NAME_1 = 'Test Game City1';
	public static final String CITY_NAME_2 = 'Test Game City2';
	public static final String BLOCK_3_C1Q1_NAME = 'Block3-C1-Q1';
	public static final String BLOCK_4_C1Q1_NAME = 'Block4-C1-Q1';
	public static final String BLOCK_1_C1Q2_NAME = 'Block1-C1-Q2';
	public static final String BLOCK_2_C2Q1_NAME = 'Block2-C2-Q1';
	
	public static CB_City__c createCity(String cityName) {
		return createCity(cityName, CB_Utils.CITY_0_IMAGE_URL);
	}
	
	public static CB_City__c createCity(String cityName, String cityImageURL) {
		CB_City__c city = new CB_City__c();
		city.CB_City_Name__c = cityName;
		city.CB_Image_URL__c = cityImageURL;
		return city;
	}
	
	public static CB_Quadrant__c createQuadrant(String quadrantName, Id cityId, Integer sequence) {
		CB_Quadrant__c quadrant = new CB_Quadrant__c();
		quadrant.CB_Quadrant_Name__c = quadrantName;
		quadrant.CB_City__c = cityId;
		quadrant.CB_Sequence__c = sequence;
		return quadrant;
	}
	
	public static CB_Block__c createBlock(String blockName, Id quadrantId, Integer sequence, Decimal cost) {
		CB_Block__c block = new CB_Block__c();
		block.CB_Block_Name__c = blockName;
		block.CB_Sequence__c = sequence;
		block.CB_Quadrant__c = quadrantId;
		block.CB_Cost__c = cost != null ? cost:5000;
		return block;
	}
	
	public static CB_Story__c createStory(String storyText, Id blockId) {
		CB_Story__c story = new CB_Story__c();
		story.CB_Story_Text__c = storyText;
		story.CB_Solution_Data_Type__c = 'Radio';
		story.CB_Block__c = blockId;
		return story;
	}
	
	public static CB_Solution_Option__c createSolutionOptions(String solutionText, Id storyId, Decimal reward, String score, Integer sequence) {
		CB_Solution_Option__c option = new CB_Solution_Option__c();
		option.CB_Story__c = storyId;
		option.CB_Sequence__c = sequence;
		option.CB_Solution_Text__c = solutionText;
		option.CB_Solution_Selection_Description__c = solutionText;
		option.CB_Reward__c = reward;
		option.CB_Score__c = score;
		return option;
	}
	
	public static CB_User_Block__c createUserBlock(Id blockId, Id gameUserId, boolean isCompleted) {
		CB_User_Block__c userBlock = new CB_User_Block__c();
		userBlock.CB_Block__c = blockId;
		userBlock.CB_Game_User__c = gameUserId;
		userBlock.CB_Completed__c = isCompleted;
		return userBlock;
	}
	
	public static CB_Story_Answer__c createStoryAnswer(Id storyId, Id gameUserId, Id solutionOptionId, Decimal wonAmount, Decimal blockCost) {
		CB_Story_Answer__c answer = new CB_Story_Answer__c();
		answer.CB_Story__c = storyId;
		answer.CB_Game_User__c = gameUserId;
		answer.CB_Solution_Option__c = solutionOptionId;
		answer.CB_Won__c = wonAmount;
		answer.CB_Block_Cost__c = blockCost;
		return answer;
	}
	
	public static CB_Game_User__c createGameUser(User u, String title, Decimal allocatedBudget) {
		CB_Game_User__c gameUser = new CB_Game_User__c();
		gameUser.Name = u.LastName;
		gameUser.CB_Title__c = title;
		gameUser.CB_User__c = u.id;
		gameUser.CB_Allocated_Budget__c = allocatedBudget;
		return gameUser;
	}
	
	public static User createTestUser(String userName, String lastName) {
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName=lastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=userName);
      	return u;     
	}
	
	/**
	 * Method to create test data will city, quadrants, Blocks, stories, Options and User Block
	 */
	public static void createTestData() {
		CB_City__c city1 = createCity(CITY_NAME_1);
    	CB_City__c city2 = createCity(CITY_NAME_2);
    	insert new List<CB_City__c>{city1, city2};
    	
    	CB_Quadrant__c quadrant11 = createQuadrant('Quadrant1 in City1', city1.id, 0);
    	CB_Quadrant__c quadrant12 = createQuadrant('Quadrant2 in City1', city1.id, 1);
    	CB_Quadrant__c quadrant21 = createQuadrant('Quadrant1 in City2', city2.id, 0);
    	insert new List<CB_Quadrant__c>{quadrant11, quadrant12, quadrant21};
    	
    	CB_Block__c block1 = createBlock('Block1-C1-Q1', quadrant11.Id, 0, 5000);
    	CB_Block__c block2 = createBlock('Block2-C1-Q1', quadrant11.Id, 1, 3000);
    	CB_Block__c block3 = createBlock(BLOCK_3_C1Q1_NAME, quadrant11.Id, 2, 4000);
    	CB_Block__c block4 = createBlock(BLOCK_4_C1Q1_NAME, quadrant11.Id, 3, 6000);
    	
    	CB_Block__c block5 = createBlock(BLOCK_1_C1Q2_NAME, quadrant12.Id, 0, 5000);
    	
    	CB_Block__c block6 = createBlock('Block1-C2-Q1', quadrant21.Id, 0, 8000); // No question for this block
    	CB_Block__c block7 = createBlock(BLOCK_2_C2Q1_NAME, quadrant21.Id, 1, 8000);
    	insert new List<CB_Block__c>{block1, block2, block3, block4, block5, block6, block7}; 
    	
    	
    	CB_Story__c storyB1 = createStory('How was your day1 today?', block1.Id);
    	CB_Story__c storyB2 = createStory('How was your day2 today?', block2.Id);
    	CB_Story__c storyB3 = createStory('How was your day3 today?', block3.Id);
    	CB_Story__c storyB4 = createStory('How was your day4 today?', block4.Id);
    	CB_Story__c storyB5 = createStory('How was your day5 today?', block5.Id);
    	CB_Story__c storyB6 = createStory('How was your day6 today?', block7.Id);
    	List<CB_Story__c> storyList = new List<CB_Story__c>{storyB1, storyB2, storyB3, storyB4, storyB5, storyB6};
    	insert storyList;
    	
    	List<CB_Solution_Option__c> solutions = new List<CB_Solution_Option__c>();
    	// Creating solution for each 6 stories. There will 3 solution for each story. So total 18 solution options will be created. 
    	for(Integer i=0; i < 6; i++) {
    		CB_Story__c story = storyList.get(i);
    		solutions.add(createSolutionOptions('It was very good', story.Id, 15000, CB_Utils.SOLUTION_OPTION_BEST, 0));
    		solutions.add(createSolutionOptions('It was very Bad', story.Id, -5000, CB_Utils.SOLUTION_OPTION_BAD, 1));
    		solutions.add(createSolutionOptions('It was Ok', story.Id, 0, CB_Utils.SOLUTION_OPTION_OK, 2));
    	}
    	insert solutions;
    	
    	// Creating solution option and User Block for Block5 and related story 
    	CB_Solution_Option__c solutionOpt = [Select Id, CB_Reward__c from CB_Solution_Option__c where CB_Story__c =:storyB5.Id and CB_Score__c =: CB_Utils.SOLUTION_OPTION_BEST limit 1];
    	
    	CB_Game_User__c gameUser = CB_Utils.getCurrentLoggedInGameUser();
    	CB_Story_Answer__c answer = createStoryAnswer(storyB5.Id, gameUser.Id, solutionOpt.Id, solutionOpt.CB_Reward__c, block5.CB_Cost__c);
    	insert answer;
    	CB_User_Block__c userBlock = createUserBlock(block5.Id, gameUser.Id, true);
    	insert userBlock;
	}
	
}