src/objects/CB_Block__c.object
<CustomObject>
    <description>This object stores the blocks associated to quadrant. We can have 4 blocks per quadrants.</description>
    <fields>
        <fullName>CB_Block_Name__c</fullName>
        <description>This field represents the Name of the Block(belongs to Quadrant), which would be displayed along with the image on the Quadrant block.</description>
        <inlineHelpText>This field represents the Name of the Quadrant, which would be displayed along with the image on the Quadrant block.</inlineHelpText>
        <label>Block Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Block</label>
    <nameField>
        <displayFormat>Block - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_Game_User__c.object
<CustomObject>
    <description>A user of City Builder Game</description>
    <label>Game User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_User_Block__c.object
<CustomObject>
    <fields>
        <fullName>CB_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the block user has completed.</description>
        <inlineHelpText>This field represents the block user has completed.</inlineHelpText>
        <label>Block</label>
        <referenceTo>CB_Block__c</referenceTo>
        <relationshipName>User_Block_Completions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the user completed this block</description>
        <inlineHelpText>Has the user completed this block</inlineHelpText>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CB_Game_User__c</fullName>
        <label>Game User</label>
        <referenceTo>CB_Game_User__c</referenceTo>
        <relationshipLabel>User Block</relationshipLabel>
        <relationshipName>User_Block_Completions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Block</label>
    <nameField>
        <displayFormat>User Block -{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CB_PlayControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of CB_PlayController Apex classes
 */
@isTest
private class CB_PlayControllerTest {
	
	/**
	 * test method for init
	 */
	 
    static testMethod void initTest() {
        CB_TestData.createTestData();
        CB_Block__c block = [Select id From CB_Block__c where CB_Block_Name__c =: CB_TestData.BLOCK_4_C1Q1_NAME limit 1];
    	
    	Test.setCurrentPage(Page.CB_Play);
    	ApexPages.currentPage().getParameters().put('blockId', block.Id);
    	
    	Test.startTest();
    	CB_PlayController controller = new CB_PlayController();
    	controller.init();
    	
    	system.assert(controller.isBlockValidToPlay );
    	system.assertEquals(CB_TestData.BLOCK_4_C1Q1_NAME, controller.block.CB_Block_Name__c);
    	
    	system.assertEquals(3, controller.solutionOptionsByScoreType.size());
    	system.assertEquals(15000, controller.solutionOptionsByScoreType.get(CB_Utils.SOLUTION_OPTION_BEST).CB_Reward__c);
    	
    	Test.stopTest();
    }
    
    /**
     * test init with -ve case where block is completed with best answer.
     */ 
    static testMethod void initBlockCompletedWithBestAnsTest() {
        CB_TestData.createTestData();
        CB_Block__c block = [Select id From CB_Block__c where CB_Block_Name__c =: CB_TestData.BLOCK_1_C1Q2_NAME limit 1];
    	
    	Test.setCurrentPage(Page.CB_Play);
    	ApexPages.currentPage().getParameters().put('blockId', block.Id);
    	
    	Test.startTest();
    	CB_PlayController controller = new CB_PlayController();
    	controller.init();
    	
    	system.assertEquals(false, controller.isBlockValidToPlay);
    	
    	List<Apexpages.Message> msgs = ApexPages.getMessages();
    	boolean hasMessage = false;
    	for(Apexpages.Message msg:msgs) {
    		if(msg.getDetail().contains(CB_Utils.BLOCK_IS_COMPLETED_WITH_BEST_ANSWER)) hasMessage = true;
    	}
    	system.assert(hasMessage);
    	
    	Test.stopTest();
    }
    
    /**
	 * test method for saveUserSelectedAnswer
	 */
    static testMethod void saveUserSelectedAnswerTest() {
        CB_TestData.createTestData();
        CB_Block__c block = [Select id From CB_Block__c where CB_Block_Name__c =: CB_TestData.BLOCK_4_C1Q1_NAME limit 1];
    	
    	Test.setCurrentPage(Page.CB_Play);
    	ApexPages.currentPage().getParameters().put('blockId', block.Id);
    	
    	CB_Game_User__c gameUser = CB_Utils.getCurrentLoggedInGameUser();
    	CB_User_Block__c userBlock = CB_Utils.getUserBlockByBlockAndGameUserId(block.Id, gameUser.Id);
    	system.assertEquals(false, userBlock.CB_Completed__c);
    	
    	Test.startTest();
    	CB_PlayController controller = new CB_PlayController();
    	controller.init();
    	
    	system.assert(controller.isBlockValidToPlay );
    	system.assertEquals(CB_TestData.BLOCK_4_C1Q1_NAME, controller.block.CB_Block_Name__c);
    	system.assertEquals(3, controller.solutionOptionsByScoreType.size());
    	
    	controller.selectedSolutionOptionId = controller.solutionOptionsByScoreType.get(CB_Utils.SOLUTION_OPTION_BEST).Id;
    	controller.saveUserSelectedAnswer();
    	
    	// Checing for User block
    	userBlock = CB_Utils.getUserBlockByBlockAndGameUserId(block.Id, gameUser.Id);
    	system.assertEquals(true, userBlock.CB_Completed__c);
    	
    	Test.stopTest();
    }
    
    /**
	 * test method for loadNextBlock
	 */
    static testMethod void loadNextBlockTest() {
        CB_TestData.createTestData();
        CB_Block__c block = [Select id From CB_Block__c where CB_Block_Name__c =: CB_TestData.BLOCK_3_C1Q1_NAME limit 1];
    	
    	Test.setCurrentPage(Page.CB_Play);
    	ApexPages.currentPage().getParameters().put('blockId', block.Id);
    	
    	CB_Game_User__c gameUser = CB_Utils.getCurrentLoggedInGameUser();
    	CB_User_Block__c userBlock = CB_Utils.getUserBlockByBlockAndGameUserId(block.Id, gameUser.Id);
    	system.assertEquals(false, userBlock.CB_Completed__c);
    	
    	Test.startTest();
    	CB_PlayController controller = new CB_PlayController();
    	controller.init();
    	
    	system.assert(controller.isBlockValidToPlay );
    	system.assertEquals(CB_TestData.BLOCK_3_C1Q1_NAME, controller.block.CB_Block_Name__c);
    	
    	PageReference ref = controller.loadNextBlock();
    	system.assert(controller.nextBlock != null);
    	system.assertEquals(CB_TestData.BLOCK_4_C1Q1_NAME, controller.nextBlock.CB_Block_Name__c);
    	
    	Test.stopTest();
    }
    
    /**
     * loadNextBlock test with not valid next block exist.
     */ 
    static testMethod void loadNextBlockNoNextBlockTest() {
        CB_TestData.createTestData();
        CB_Block__c block = [Select id From CB_Block__c where CB_Block_Name__c =: CB_TestData.BLOCK_2_C2Q1_NAME limit 1];
    	
    	Test.setCurrentPage(Page.CB_Play);
    	ApexPages.currentPage().getParameters().put('blockId', block.Id);
    	
    	CB_Game_User__c gameUser = CB_Utils.getCurrentLoggedInGameUser();
    	CB_User_Block__c userBlock = CB_Utils.getUserBlockByBlockAndGameUserId(block.Id, gameUser.Id);
    	system.assertEquals(false, userBlock.CB_Completed__c);
    	
    	Test.startTest();
    	CB_PlayController controller = new CB_PlayController();
    	controller.init();
    	
    	system.assert(controller.isBlockValidToPlay );
    	system.assertEquals(CB_TestData.BLOCK_2_C2Q1_NAME, controller.block.CB_Block_Name__c);
    	
    	PageReference ref = controller.loadNextBlock();
    	system.assert(controller.nextBlock == null);
    	system.assertEquals(false, controller.isBlockValidToPlay);
    	
    	List<Apexpages.Message> msgs = ApexPages.getMessages();
    	boolean hasMessage = false;
    	for(Apexpages.Message msg:msgs) {
    		if(msg.getDetail().contains(CB_Utils.ALL_QUADRANTS_AND_BLOCKS_COMPLETE)) hasMessage = true;
    	}
    	system.assert(hasMessage);
    	system.assertEquals(CB_Utils.OPPS_MESSAGE, controller.oopsModalMessage);
    	system.assertEquals(CB_Utils.NOT_BAD_MESSAGE, controller.notBadModalMessage);
    	system.assertEquals(CB_Utils.BEST_MESSAGE, controller.successModalMessage);
    	
    	Test.stopTest();
    }
}