src/objects/CB_Block__c.object
<CustomObject>
    <description>This object stores the blocks associated to quadrant. We can have 4 blocks per quadrants.</description>
    <fields>
        <fullName>CB_Cost__c</fullName>
        <description>Cost of Opening the block</description>
        <inlineHelpText>Cost of Opening the block</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Quadrant__c</fullName>
        <description>Quadrant to which this block belongs.</description>
        <inlineHelpText>Quadrant to which this block belongs.</inlineHelpText>
        <label>Quadrant</label>
        <referenceTo>CB_Quadrant__c</referenceTo>
        <relationshipLabel>Block</relationshipLabel>
        <relationshipName>Block</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>Sequence of the Block to be shown on the UI, It will also maintain the levels.</description>
        <inlineHelpText>Sequence of the Block to be shown on the UI, It will also maintain the levels.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Block</label>
    <nameField>
        <displayFormat>Block - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_City__c.object
<CustomObject>
    <description>The Master City records</description>
    <label>City</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

demoOrg/objects/CB_Game_User__c.object
<CustomObject>
    <description>A user of City Builder Game</description>
    <label>Game User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Quadrant__c.object
<CustomObject>
    <description>One city may contain multiple Quadrant. One quadrant is made up of 4 blocks.</description>
    <fields>
        <fullName>CB_City__c</fullName>
        <description>This field represents the Master detail relationship with the city object.</description>
        <inlineHelpText>City to which quadrant belongs</inlineHelpText>
        <label>City</label>
        <referenceTo>CB_City__c</referenceTo>
        <relationshipLabel>Quadrants</relationshipLabel>
        <relationshipName>Quadrants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>Sequence of the Quadrant to be shown on the UI, It will also maintain the levels.</description>
        <inlineHelpText>Sequence of the Quadrant to be shown on the UI, It will also maintain the levels.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quadrant</label>
    <nameField>
        <displayFormat>Quadrant - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quadrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

demoOrg/objects/CB_Solution_Option__c.object
<CustomObject>
    <description>Each story has a set of solutions. These are configurable, means we can configure the datatype of the solution options.</description>
    <fields>
        <fullName>CB_Reward__c</fullName>
        <description>Amount is 1.72 for Best Option, 0 for OK Option, and -2.0 for Bad Option</description>
        <formula>CASE(CB_Score__c,
     &quot;Bad&quot;, -1 * (CB_Story__r.CB_Block__r.CB_Cost__c * 2.0),
     &quot;Best&quot;,CB_Story__r.CB_Block__r.CB_Cost__c * 1.72,
     0 )</formula>
        <inlineHelpText>Amount is 1.72 for Best Option, 0 for OK Option, and -2.0 for Bad Option</inlineHelpText>
        <label>Reward</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Score__c</fullName>
        <description>Score would assigned to each Solution option. Based on the solution option selection and score further actions would be taken.</description>
        <inlineHelpText>Score would assigned to each Solution option. Based on the solution option selection and score further actions would be taken.</inlineHelpText>
        <label>Score</label>
        <picklist>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CB_Sequence__c</fullName>
        <description>This field maintains the Sequence in which solution options to be displayed.</description>
        <inlineHelpText>This field maintains the Sequence in which solution options to be displayed.</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CB_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Story to which solution belongs.</description>
        <inlineHelpText>Story to which solution belongs.</inlineHelpText>
        <label>Story</label>
        <referenceTo>CB_Story__c</referenceTo>
        <relationshipLabel>Solutions Options</relationshipLabel>
        <relationshipName>Solutions_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution Option</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Solution Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Story__c.object
<CustomObject>
    <description>Each block has one scenario (story) that the player reads. This object stores the stories associated with blocks.</description>
    <fields>
        <fullName>CB_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the relation to Block object.</description>
        <inlineHelpText>Block to which Story belongs</inlineHelpText>
        <label>Block</label>
        <referenceTo>CB_Block__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>Story - {0000}</displayFormat>
        <label>Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CB_Story_Answer__c.object
<CustomObject>
    <description>User Selected Answer for the Story</description>
    <fields>
        <fullName>CB_Block_Cost__c</fullName>
        <description>Cost of the Block for this Story</description>
        <inlineHelpText>Cost of the Block for this Story</inlineHelpText>
        <label>Block Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CB_Game_User__c</fullName>
        <label>Game User</label>
        <referenceTo>CB_Game_User__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>CB_Game_User</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CB_Solution_Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The solution, user has selected for their story.</description>
        <inlineHelpText>The solution, user has selected for their story.</inlineHelpText>
        <label>Solution Option</label>
        <referenceTo>CB_Solution_Option__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>Solution_Option</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>CB_Story__c</referenceTo>
        <relationshipLabel>Story Answer</relationshipLabel>
        <relationshipName>Story_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Won__c</fullName>
        <description>Amount won by the user, on selecting the option</description>
        <inlineHelpText>Amount won by the user, on selecting the option.</inlineHelpText>
        <label>Won</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Story Answer</label>
    <nameField>
        <displayFormat>Story Answer - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Story Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CB_User_Block__c.object
<CustomObject>
    <fields>
        <fullName>CB_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the block user has completed.</description>
        <inlineHelpText>This field represents the block user has completed.</inlineHelpText>
        <label>Block</label>
        <referenceTo>CB_Block__c</referenceTo>
        <relationshipName>User_Block_Completions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CB_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the user completed this block</description>
        <inlineHelpText>Has the user completed this block</inlineHelpText>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CB_Game_User__c</fullName>
        <label>Game User</label>
        <referenceTo>CB_Game_User__c</referenceTo>
        <relationshipLabel>User Block</relationshipLabel>
        <relationshipName>User_Block_Completions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Block</label>
    <nameField>
        <displayFormat>User Block -{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Block</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

demoOrg/classes/CB_PlayController.cls
/**
 * Class holding logic to play for a selected block. The logic checks if selected block is valid to play or not.
 */
public with sharing class CB_PlayController {
	// Story detail for game user to answer
	public CB_Story__c story {get; private set;}
	
	// Current block detail 
	public CB_Block__c block {get; private set;}
	
	// Map holding Solution Options with key as solution type (Bad, OK and Best) and value as Solution Option Record corresponding to that type.
	public Map<String, CB_Solution_Option__c> solutionOptionsByScoreType {get; private set;}
	
	// Next valid block for game user to play
	public CB_Block__c nextBlock {get; private set;}
	
	// Variable to hold the id of the selected Solution Option answer
	public String selectedSolutionOptionId {get;set;}
	
	public boolean isBlockValidToPlay {get;set;}
	
	private CB_Game_User__c gameUser;
	
	/**
	 * Init method to load block details and validate if current block is valid to play or not.
	 */
	public void init() {
		// get the blockId
		Id blockId = (Id)ApexPages.currentPage().getParameters().get('blockId');
		this.isBlockValidToPlay = true;
		try {
			// Getting block detail using the block id
			block = CB_Utils.getBlockInfoByBlockId(blockId);
			
			// get the current logged in game user.
			gameUser = CB_Utils.getCurrentLoggedInGameUser();
			
			// getting the story and related Solutions Options associated with the block
			story = CB_Utils.getStoriesByBlockId(blockId, gameUser.Id);
			
			this.isBlockValidToPlay = CB_Utils.isBlockValidForCurrentUserToPlay(block, story, gameUser);
			// Preparing the solutionOptions with key as score type and value as solutionOption record.
			solutionOptionsByScoreType = CB_Utils.getSolutionOptionsByScoreType(this.story.Solutions_Options__r);
		} catch(Exception e) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
			this.isBlockValidToPlay = false;
		}
	}
	
	/**
	 * Method to save the user selected answer and updating the User Block record to completed if the selected 
	 * answer is best or OK. 
	 */
	public void saveUserSelectedAnswer() {
		Savepoint sp = Database.setSavepoint();
		try {
			// Converting the Solution Options from story to Map(key as id and value as record).
			Map<Id, CB_Solution_Option__c> solutionOptionByIdMap = new Map<Id, CB_Solution_Option__c>(this.story.Solutions_Options__r);
			
			CB_Game_User__c gameUser = CB_Utils.getCurrentLoggedInGameUser();
			
			// Getting User Block record for block id and game user passed as argument.
			CB_User_Block__c userBlock = CB_Utils.getUserBlockByBlockAndGameUserId(this.block.Id, gameUser.Id);
			
			CB_Story_Answer__c storyAnswer = new CB_Story_Answer__c();
			storyAnswer.CB_Story__c = this.story.Id;
			storyAnswer.CB_Solution_Option__c = this.selectedSolutionOptionId;
			storyAnswer.CB_Game_User__c = gameUser.Id;
			storyAnswer.CB_Block_Cost__c = this.block.CB_Cost__c;
			CB_Solution_Option__c solutionOption = solutionOptionByIdMap.get(this.selectedSolutionOptionId);
			Double reward = solutionOption.CB_Reward__c;
			storyAnswer.CB_Won__c = reward;
			insert storyAnswer;
			
			// marking the userBlock as completed if selected solution option score is either OK or Best.
			if(solutionOption.CB_Score__c == CB_Utils.SOLUTION_OPTION_OK || solutionOption.CB_Score__c == CB_Utils.SOLUTION_OPTION_BEST){
				userBlock.CB_Completed__c = true;
				update userBlock;
			}
		}catch(Exception e) {
			Database.rollback(sp);
			this.isBlockValidToPlay = false;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
		}
	}
	
	/**
	 * Method to get load the next valid block for user to play next. 
	 */
	public PageReference loadNextBlock() {
		PageReference ref = null;
		try {
			// Get the next valid block for the game user to play after this block.
			nextBlock = CB_Utils.getNextBlockToPlay(this.block.CB_Sequence__c, this.block.CB_Quadrant__r.CB_Sequence__c, this.block.CB_Quadrant__c, this.block.CB_Quadrant__r.CB_City__c, this.gameUser);
			
			// if nextblock - null, throw exception with message - all quadrants and blocks complete 
			if(nextBlock == null) throw new CB_Utils.CB_GameException(CB_Utils.ALL_QUADRANTS_AND_BLOCKS_COMPLETE);
			
			ref = Page.CB_Play;
			ref.getParameters().put('blockId', nextBlock.id);
			ref.setRedirect(true);
		} catch(Exception e) {
			this.isBlockValidToPlay = false;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
		}
		return ref;
	}
	
	// Message variables used on VF page 
	public String oopsModalMessage { get { return CB_Utils.OPPS_MESSAGE; } set;}
	public String notBadModalMessage { get { return CB_Utils.NOT_BAD_MESSAGE; } set;}
	public String successModalMessage { get { return CB_Utils.BEST_MESSAGE; } set;}
}